php artisan make:model Piece -a
php artisan make:model Bateau -a
php artisan make:model Utilisateur -a
php artisan make:model Entretien -a
php artisan make:model Adresse -a
php artisan make:model Equipement -a
php artisan make:model permis -a
php artisan make:model Fournisseur -a
php artisan make:model Etat -a
php artisan make:model Modele -a
php artisan make:model Marque -a
php artisan make:model Typiece -a
php artisan make:model Typequipement -a
php artisan make:model Immatriculation -a
php artisan make:model Moteur -a
php artisan make:model Port -a
php artisan make:model Accident -a
php artisan make:model Ville -a
php artisan make:model Pays -a
php artisan make:model Possède -a
php artisan make:model A_passé -a
php artisan make:model utilise_couramment -a
php artisan make:model Necessite -a
php artisan make:model est_impliqué -a
php artisan make:model contient -a
php artisan make:model comporte -a
php artisan make:model reçoit -a
php artisan make:model concerne -a
php artisan make:model est_composé -a
php artisan make:model produit_par -a
php artisan make:model est_renseigné_sous -a
php artisan make:model fournit -a
php artisan make:model est_localisé -a
php artisan make:model est_dans -a
