php artisan make:model Piece --controller --resource
php artisan make:model Bateau --controller --resource
php artisan make:model Utilisateur --controller --resource
php artisan make:model Entretien --controller --resource
php artisan make:model Adresse --controller --resource
php artisan make:model Equipement --controller --resource
php artisan make:model permis --controller --resource
php artisan make:model Fournisseur --controller --resource
php artisan make:model Etat --controller --resource
php artisan make:model Modele --controller --resource
php artisan make:model Marque --controller --resource
php artisan make:model Typiece --controller --resource
php artisan make:model Typequipement --controller --resource
php artisan make:model Immatriculation --controller --resource
php artisan make:model Moteur --controller --resource
php artisan make:model Port --controller --resource
php artisan make:model Accident --controller --resource
php artisan make:model Ville --controller --resource
php artisan make:model Pays --controller --resource
php artisan make:model Possède --controller --resource
php artisan make:model A_passé --controller --resource
php artisan make:model utilise_couramment --controller --resource
php artisan make:model Necessite --controller --resource
php artisan make:model est_impliqué --controller --resource
php artisan make:model contient --controller --resource
php artisan make:model comporte --controller --resource
php artisan make:model reçoit --controller --resource
php artisan make:model concerne --controller --resource
php artisan make:model est_composé --controller --resource
php artisan make:model produit_par --controller --resource
php artisan make:model est_renseigné_sous --controller --resource
php artisan make:model fournit --controller --resource
php artisan make:model est_localisé --controller --resource
php artisan make:model est_dans --controller --resource
